name: agni_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.7+3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  # curved_navigation_bar: ^0.3.3
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  flutter_video_compress: ^0.3.7+8
  video_player: '>=0.10.11+2 <2.0.0'
  cached_network_image: ^2.2.0+1
  http: ^0.12.2
  provider: ^4.3.1
  camera: ^0.5.8+2
  cupertino_icons: ^0.1.3
  file_picker: ^1.13.0+1
  font_awesome_flutter: ^8.8.1
  threading: ^0.0.10
  uuid: ^2.2.0
  percent_indicator: ^2.1.5
  async: ^2.4.1
  dio: ^3.0.9
  lamp: ^0.0.6
  flushbar: ^1.10.4
  google_fonts: ^1.1.0
  progress_dialog: ^1.2.4
  intl: ^0.16.1
  timeago: ^2.0.26
  firebase_messaging: ^6.0.16
  get_it: ^4.0.2
  visibility_detector: ^0.1.5
  flutter_absolute_path: ^1.0.6
  audioplayers: ^0.15.1
  flutter_ffmpeg: ^0.2.10
  # flutter_downloader: ^1.5.0
  # simple_permissions: ^0.1.9
  file_utils: ^0.1.3
  random_string: ^2.0.1
  cloud_firestore: ^0.14.0+1
  firebase_core: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/icons/
      - assets/images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
